// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from "@/models/auth.ts";

export const models = {
  model_1: { namespace: "useAuthModel", model: model_1 },
  // model_2: { namespace: 'useViewModel', model: model_2 },
};
